name: CI
on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build,
      run: |
        yarn install
        yarn build
    - name: showFiles,
      run: |
        mv './src/dist/* .'
        rm -rf './babel.config.js node_modules/ package.json public/ src/ vue.config.js yarn.lock'
      env:
        CI: true
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./
